// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function evenFibSum(max_value, _prev_num, _prev_prev_num, _even_sum) {
  while(true) {
    var even_sum = _even_sum;
    var prev_prev_num = _prev_prev_num;
    var prev_num = _prev_num;
    var new_num = prev_num + prev_prev_num | 0;
    if (new_num > max_value) {
      return even_sum;
    } else {
      var new_sum = new_num % 2 === 0 ? even_sum + new_num | 0 : even_sum;
      _even_sum = new_sum;
      _prev_prev_num = prev_num;
      _prev_num = new_num;
      continue ;
    }
  };
}

var sum = evenFibSum(4000000, 0, 1, 0);

console.log("Problem 002: " + (String(sum) + ""));

exports.evenFibSum = evenFibSum;
exports.sum = sum;
/* sum Not a pure module */
